ALTER TABLE alerts
ADD COLUMN IF NOT EXISTS occurrence_count INTEGER DEFAULT 1;

UPDATE alerts
SET occurrence_count = 1
WHERE occurrence_count IS NULL;

ALTER TABLE commands
ADD COLUMN IF NOT EXISTS result VARCHAR;

ALTER TABLE commands
ADD COLUMN IF NOT EXISTS error VARCHAR;

ALTER TABLE commands
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
