"""
PDF report generator using reportlab.

Three report types:
  daily_soc           — 24-hour SOC operations summary
  weekly_exec         — 7-day executive summary
  monthly_compliance  — 30-day compliance overview
"""
from __future__ import annotations

import io
from datetime import datetime

from sqlalchemy.orm import Session
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)

from app.models.alert import Alert
from app.models.incident import Incident
from app.models.agent import Agent
from app.models.command import Command


# ── Colour palette ─────────────────────────────────────────────────────────────

_BRAND   = colors.HexColor("#1E3A5F")
_ACCENT  = colors.HexColor("#E63946")
_LIGHT   = colors.HexColor("#F1F5F9")
_BORDER  = colors.HexColor("#CBD5E1")
_TEXT    = colors.HexColor("#1E293B")
_MUTED   = colors.HexColor("#64748B")


# ── Shared helpers ─────────────────────────────────────────────────────────────

def _styles():
    ss = getSampleStyleSheet()
    custom = {
        "Title": ParagraphStyle(
            "Title", parent=ss["Normal"],
            fontSize=22, textColor=_BRAND, spaceAfter=4, spaceBefore=0,
            fontName="Helvetica-Bold",
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle", parent=ss["Normal"],
            fontSize=11, textColor=_MUTED, spaceAfter=16,
            fontName="Helvetica",
        ),
        "SectionHeader": ParagraphStyle(
            "SectionHeader", parent=ss["Normal"],
            fontSize=13, textColor=_BRAND, spaceBefore=18, spaceAfter=6,
            fontName="Helvetica-Bold",
        ),
        "Body": ParagraphStyle(
            "Body", parent=ss["Normal"],
            fontSize=9, textColor=_TEXT, leading=14,
            fontName="Helvetica",
        ),
        "Small": ParagraphStyle(
            "Small", parent=ss["Normal"],
            fontSize=8, textColor=_MUTED, leading=12,
            fontName="Helvetica",
        ),
    }
    return custom


def _kv_table(pairs: list[tuple[str, str]]) -> Table:
    """Two-column key-value summary table."""
    data = [[Paragraph(k, ParagraphStyle("k", fontName="Helvetica-Bold", fontSize=9, textColor=_MUTED)),
             Paragraph(str(v), ParagraphStyle("v", fontName="Helvetica", fontSize=9, textColor=_TEXT))]
            for k, v in pairs]
    t = Table(data, colWidths=[5 * cm, 11 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _LIGHT),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, _LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, _BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def _data_table(headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None) -> Table:
    header_style = ParagraphStyle("th", fontName="Helvetica-Bold", fontSize=8, textColor=colors.white)
    cell_style   = ParagraphStyle("td", fontName="Helvetica", fontSize=8, textColor=_TEXT)
    data = [[Paragraph(h, header_style) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), cell_style) for c in row])
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _BRAND),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, _BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def _fmt(dt: datetime | None) -> str:
    return dt.strftime("%Y-%m-%d %H:%M UTC") if dt else "—"


def _header_block(story: list, st: dict, title: str, subtitle: str) -> None:
    story.append(Paragraph(title, st["Title"]))
    story.append(Paragraph(subtitle, st["Subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=_BRAND, spaceAfter=12))


def _footer_note(story: list, st: dict) -> None:
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_BORDER))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(
        "Generated by NetcradXDR  ·  Confidential — for authorised personnel only",
        st["Small"],
    ))


def _build_pdf(story: list) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=2 * cm, leftMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    doc.build(story)
    return buf.getvalue()


# ── Alert query helpers ────────────────────────────────────────────────────────

def _alert_stats(db: Session, tenant_id: int, start: datetime, end: datetime) -> dict:
    base = (db.query(Alert)
            .join(Agent, Alert.agent_id == Agent.id)
            .filter(Agent.tenant_id == tenant_id,
                    Alert.timestamp >= start,
                    Alert.timestamp < end))
    total    = base.count()
    critical = base.filter(Alert.severity == "Critical").count()
    high     = base.filter(Alert.severity == "High").count()
    medium   = base.filter(Alert.severity == "Medium").count()
    low      = base.filter(Alert.severity == "Low").count()
    resolved = base.filter(Alert.status == "Resolved").count()
    recent   = (base.order_by(Alert.timestamp.desc()).limit(10).all())
    return {
        "total": total, "critical": critical, "high": high,
        "medium": medium, "low": low, "resolved": resolved, "recent": recent,
    }


def _incident_stats(db: Session, tenant_id: int, start: datetime, end: datetime) -> dict:
    base = (db.query(Incident)
            .filter(Incident.tenant_id == tenant_id,
                    Incident.created_at >= start,
                    Incident.created_at < end))
    total    = base.count()
    open_    = base.filter(Incident.status == "Open").count()
    resolved = base.filter(Incident.status == "Resolved").count()
    recent   = base.order_by(Incident.created_at.desc()).limit(8).all()
    return {"total": total, "open": open_, "resolved": resolved, "recent": recent}


def _agent_stats(db: Session, tenant_id: int) -> dict:
    total  = db.query(Agent).filter(Agent.tenant_id == tenant_id).count()
    online = db.query(Agent).filter(Agent.tenant_id == tenant_id, Agent.status == "Online").count()
    return {"total": total, "online": online}


# ── Daily SOC report ──────────────────────────────────────────────────────────

def generate_daily_soc(db: Session, tenant_id: int, period_start: datetime, period_end: datetime) -> bytes:
    st    = _styles()
    story = []

    _header_block(
        story, st,
        "Daily SOC Operations Report",
        f"Period: {_fmt(period_start)}  →  {_fmt(period_end)}",
    )

    alerts   = _alert_stats(db, tenant_id, period_start, period_end)
    incidents = _incident_stats(db, tenant_id, period_start, period_end)
    agents   = _agent_stats(db, tenant_id)

    # Summary KPIs
    story.append(Paragraph("Executive Summary", st["SectionHeader"]))
    story.append(_kv_table([
        ("Total Alerts",      str(alerts["total"])),
        ("  Critical / High", f"{alerts['critical']} / {alerts['high']}"),
        ("  Resolved",        str(alerts["resolved"])),
        ("Total Incidents",   str(incidents["total"])),
        ("  Open / Resolved", f"{incidents['open']} / {incidents['resolved']}"),
        ("Monitored Endpoints", f"{agents['online']} online of {agents['total']} total"),
    ]))
    story.append(Spacer(1, 0.4 * cm))

    # Recent alerts table
    story.append(Paragraph("Recent Alerts (last 10)", st["SectionHeader"]))
    if alerts["recent"]:
        rows = [
            [_fmt(a.timestamp), a.severity or "—", a.title or "—", a.status or "—"]
            for a in alerts["recent"]
        ]
        story.append(_data_table(
            ["Timestamp", "Severity", "Title", "Status"],
            rows,
            col_widths=[4 * cm, 2.5 * cm, 9 * cm, 2.5 * cm],
        ))
    else:
        story.append(Paragraph("No alerts in this period.", st["Body"]))
    story.append(Spacer(1, 0.4 * cm))

    # Recent incidents table
    story.append(Paragraph("Recent Incidents", st["SectionHeader"]))
    if incidents["recent"]:
        rows = [
            [_fmt(i.created_at), i.severity or "—", i.title or "—", i.status or "—"]
            for i in incidents["recent"]
        ]
        story.append(_data_table(
            ["Created", "Severity", "Title", "Status"],
            rows,
            col_widths=[4 * cm, 2.5 * cm, 9 * cm, 2.5 * cm],
        ))
    else:
        story.append(Paragraph("No incidents in this period.", st["Body"]))

    _footer_note(story, st)
    return _build_pdf(story)


# ── Weekly executive report ────────────────────────────────────────────────────

def generate_weekly_executive(db: Session, tenant_id: int, period_start: datetime, period_end: datetime) -> bytes:
    st    = _styles()
    story = []

    _header_block(
        story, st,
        "Weekly Executive Security Report",
        f"Week of {period_start.strftime('%B %d, %Y')}  —  Generated {datetime.utcnow().strftime('%Y-%m-%d')}",
    )

    alerts    = _alert_stats(db, tenant_id, period_start, period_end)
    incidents = _incident_stats(db, tenant_id, period_start, period_end)
    agents    = _agent_stats(db, tenant_id)

    story.append(Paragraph("Security Posture Overview", st["SectionHeader"]))
    story.append(_kv_table([
        ("Report Period",         f"{_fmt(period_start)} → {_fmt(period_end)}"),
        ("Total Alerts",          str(alerts["total"])),
        ("Critical Alerts",       str(alerts["critical"])),
        ("High Alerts",           str(alerts["high"])),
        ("Alert Resolution Rate", f"{int(alerts['resolved'] / max(alerts['total'], 1) * 100)}%"),
        ("Total Incidents",       str(incidents["total"])),
        ("Open Incidents",        str(incidents["open"])),
        ("Resolved Incidents",    str(incidents["resolved"])),
        ("Endpoints Monitored",   f"{agents['online']} online / {agents['total']} total"),
    ]))
    story.append(Spacer(1, 0.4 * cm))

    # Alert severity breakdown
    story.append(Paragraph("Alert Severity Breakdown", st["SectionHeader"]))
    story.append(_data_table(
        ["Severity", "Count", "% of Total"],
        [
            ["Critical", str(alerts["critical"]),
             f"{int(alerts['critical'] / max(alerts['total'], 1) * 100)}%"],
            ["High", str(alerts["high"]),
             f"{int(alerts['high'] / max(alerts['total'], 1) * 100)}%"],
            ["Medium", str(alerts["medium"]),
             f"{int(alerts['medium'] / max(alerts['total'], 1) * 100)}%"],
            ["Low", str(alerts["low"]),
             f"{int(alerts['low'] / max(alerts['total'], 1) * 100)}%"],
        ],
        col_widths=[4 * cm, 4 * cm, 4 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Key Incidents This Week", st["SectionHeader"]))
    if incidents["recent"]:
        rows = [
            [_fmt(i.created_at), i.severity or "—", i.title or "—", i.status or "—"]
            for i in incidents["recent"]
        ]
        story.append(_data_table(
            ["Created", "Severity", "Title", "Status"],
            rows,
            col_widths=[4 * cm, 2.5 * cm, 9 * cm, 2.5 * cm],
        ))
    else:
        story.append(Paragraph("No incidents recorded this week.", st["Body"]))

    _footer_note(story, st)
    return _build_pdf(story)


# ── Monthly compliance report ─────────────────────────────────────────────────

def generate_monthly_compliance(db: Session, tenant_id: int, period_start: datetime, period_end: datetime) -> bytes:
    st    = _styles()
    story = []

    _header_block(
        story, st,
        "Monthly Compliance & Security Report",
        f"{period_start.strftime('%B %Y')}  —  Generated {datetime.utcnow().strftime('%Y-%m-%d')}",
    )

    alerts    = _alert_stats(db, tenant_id, period_start, period_end)
    incidents = _incident_stats(db, tenant_id, period_start, period_end)
    agents    = _agent_stats(db, tenant_id)

    commands_run = (
        db.query(Command)
        .join(Agent, Command.agent_id == Agent.id)
        .filter(Agent.tenant_id == tenant_id,
                Command.created_at >= period_start,
                Command.created_at < period_end)
        .count()
    )

    story.append(Paragraph("Monthly Summary", st["SectionHeader"]))
    story.append(_kv_table([
        ("Report Month",          period_start.strftime("%B %Y")),
        ("Total Alerts",          str(alerts["total"])),
        ("Critical Alerts",       str(alerts["critical"])),
        ("Alert Resolution Rate", f"{int(alerts['resolved'] / max(alerts['total'], 1) * 100)}%"),
        ("Total Incidents",       str(incidents["total"])),
        ("Resolved Incidents",    str(incidents["resolved"])),
        ("Open Incidents",        str(incidents["open"])),
        ("Endpoints Monitored",   f"{agents['total']} total ({agents['online']} online)"),
        ("Response Actions Taken", str(commands_run)),
    ]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Compliance Notes", st["SectionHeader"]))
    story.append(Paragraph(
        "All security events have been logged and are available for audit review. "
        "Incident response procedures were followed per the defined playbooks. "
        "Endpoint monitoring coverage is reported above. "
        "This report is generated automatically by NetcradXDR.",
        st["Body"],
    ))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Alert Severity Distribution", st["SectionHeader"]))
    story.append(_data_table(
        ["Severity", "Count", "% of Total", "Notes"],
        [
            ["Critical", str(alerts["critical"]),
             f"{int(alerts['critical'] / max(alerts['total'], 1) * 100)}%",
             "Immediate response required"],
            ["High", str(alerts["high"]),
             f"{int(alerts['high'] / max(alerts['total'], 1) * 100)}%",
             "Respond within 4 hours"],
            ["Medium", str(alerts["medium"]),
             f"{int(alerts['medium'] / max(alerts['total'], 1) * 100)}%",
             "Respond within 24 hours"],
            ["Low", str(alerts["low"]),
             f"{int(alerts['low'] / max(alerts['total'], 1) * 100)}%",
             "Review in weekly cycle"],
        ],
        col_widths=[3.5 * cm, 3 * cm, 3.5 * cm, 8 * cm],
    ))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Top Incidents", st["SectionHeader"]))
    if incidents["recent"]:
        rows = [
            [_fmt(i.created_at), i.severity or "—", i.title or "—", i.status or "—"]
            for i in incidents["recent"]
        ]
        story.append(_data_table(
            ["Created", "Severity", "Title", "Status"],
            rows,
            col_widths=[4 * cm, 2.5 * cm, 9 * cm, 2.5 * cm],
        ))
    else:
        story.append(Paragraph("No incidents recorded this month.", st["Body"]))

    _footer_note(story, st)
    return _build_pdf(story)


# ── Dispatch helper ────────────────────────────────────────────────────────────

GENERATORS = {
    "daily_soc":           generate_daily_soc,
    "weekly_exec":         generate_weekly_executive,
    "monthly_compliance":  generate_monthly_compliance,
}


def generate_report(
    db: Session,
    tenant_id: int,
    report_type: str,
    period_start: datetime,
    period_end: datetime,
) -> bytes:
    fn = GENERATORS.get(report_type)
    if fn is None:
        raise ValueError(f"Unknown report type: {report_type}")
    return fn(db, tenant_id, period_start, period_end)
